name: Nuget Release

on:
  push:
    branch:
      - develop

    # Publish `v1.2.3` tags as releases.
    #tags:
    #  - v*

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      #- name: Test
      #  run: dotnet test --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack -p:Version=2.0.0-alpha --include-symbols --include-source --no-restore --configuration Release --verbosity normal

      - name: Push API Client
        run: dotnet nuget push src/Ngrok.AspNetCore/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/kg73/index.json"

      - name: Push Ngrok Library
        run: dotnet nuget push src/Ngrok.ApiClient/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/kg73/index.json"
    
